# Bank Marketing

[Master Tree Ensemble Models course](https://www.trainindata.com/p/master-tree-ensemble-models)

In this notebook, we prepare the Bank Marketing dataset for the course.

The data comes from a direct marketing campaign of a Portuguese bank. The goal is to predict whether a client subscribes to a term deposit.

Here, we load the data from OpenML, encode the target as 0 and 1, give the variables descriptive names, and set the categorical variables to the category data type. Then, we save the data as a parquet file.

Dataset: [Bank Marketing](https://archive.ics.uci.edu/dataset/222/bank+marketing)

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml

In [2]:
data = fetch_openml(
    name="bank-marketing",
    version=1,
    as_frame=True,
    parser="auto",
)

X = data.data.copy()
y = (data.target == "2").astype(int)

In [3]:
X.columns = [
    "age",
    "job",
    "marital",
    "education",
    "default",
    "balance",
    "housing",
    "loan",
    "contact",
    "day",
    "month",
    "duration",
    "campaign",
    "pdays",
    "previous",
    "poutcome",
]

In [4]:
X["pdays"] = X["pdays"].replace(-1, np.nan)
categorical_cols = [
    "job",
    "marital",
    "education",
    "default",
    "housing",
    "loan",
    "contact",
    "month",
    "poutcome",
]
X[categorical_cols] = X[categorical_cols].astype("category")
X.dtypes

age             int64
job          category
marital      category
education    category
default      category
balance         int64
housing      category
loan         category
contact      category
day             int64
month        category
duration        int64
campaign        int64
pdays         float64
previous        int64
poutcome     category
dtype: object

In [5]:
X.isnull().sum()

age              0
job              0
marital          0
education        0
default          0
balance          0
housing          0
loan             0
contact          0
day              0
month            0
duration         0
campaign         0
pdays        36954
previous         0
poutcome         0
dtype: int64

In [6]:
X.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,NaN,0,unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,NaN,0,unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,NaN,0,unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,NaN,0,unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,NaN,0,unknown

In [7]:
df = pd.concat([X, y.rename("y")], axis=1)
df.to_parquet("bank_marketing.parquet")
df.to_csv("bank_marketing.csv", index=False)

In [8]:
df = pd.read_parquet("bank_marketing.parquet")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,NaN,0,unknown,0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,NaN,0,unknown,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,NaN,0,unknown,0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,NaN,0,unknown,0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,NaN,0,unknown,0